file_format: "1"
id: nicepad
name: nicepad
type: shield
url: https://github.com/Bastardkb/TBK-Mini
# requires: [Nice!Nano]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
# siblings:
  # - corne_left
  # - corne_right
